<a href="https://colab.research.google.com/github/aniray2908/nlp-llm-journey/blob/main/00_pytorch_warmup/01_tensors_slicing_broadcasting_gpu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise Set 1 — Tensors & Slicing

## 1. Create and inspect

In [1]:
import torch
x = torch.randn(5, 4)

In [2]:
x.shape

torch.Size([5, 4])

In [3]:
x.dtype

torch.float32

In [4]:
x.device

device(type='cpu')

In [5]:
x[4]

tensor([ 0.0663, -0.7156,  0.0492, -1.2044])

In [6]:
x[3]

tensor([-0.4299,  0.3244,  0.1608, -0.5062])

## 2. Slicing challenge

In [7]:
x = torch.arange(1, 26).reshape(5, 5)

In [8]:
x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])

In [9]:
x[1:4,1:4]

tensor([[ 7,  8,  9],
        [12, 13, 14],
        [17, 18, 19]])

In [10]:
x[::2]

tensor([[ 1,  2,  3,  4,  5],
        [11, 12, 13, 14, 15],
        [21, 22, 23, 24, 25]])

In [12]:
x[range(5), range(5)]

tensor([ 1,  7, 13, 19, 25])

In [44]:
torch.diag(x)

tensor([ 1,  7, 13, 19, 25])

## 3. Manipulation

In [27]:
x = torch.randn(3, 4)
x

tensor([[-0.9879,  1.2677,  1.1883,  0.0942],
        [-0.0444, -0.7228,  0.2047,  0.6812],
        [ 0.6689,  1.3984,  0.3360, -0.0307]])

In [28]:
x.reshape(4,3)

tensor([[-0.9879,  1.2677,  1.1883],
        [ 0.0942, -0.0444, -0.7228],
        [ 0.2047,  0.6812,  0.6689],
        [ 1.3984,  0.3360, -0.0307]])

In [29]:
x.reshape(2,6)

tensor([[-0.9879,  1.2677,  1.1883,  0.0942, -0.0444, -0.7228],
        [ 0.2047,  0.6812,  0.6689,  1.3984,  0.3360, -0.0307]])

In [30]:
x.reshape(3,4)

tensor([[-0.9879,  1.2677,  1.1883,  0.0942],
        [-0.0444, -0.7228,  0.2047,  0.6812],
        [ 0.6689,  1.3984,  0.3360, -0.0307]])

In [31]:
x=x.T

In [32]:
x.shape

torch.Size([4, 3])

In [33]:
x.sum(dim=0).shape

torch.Size([3])

In [34]:
x.sum(dim=1).shape

torch.Size([4])

# Exercise Set 2 — Broadcasting

## 4. Predict before running

In [35]:
a = torch.ones(3, 4)
b = torch.ones(4)
c = a + b

In [36]:
c.shape

torch.Size([3, 4])

In [37]:
d = torch.ones(3, 1)
e = torch.ones(1, 4)
f = d + e

In [38]:
f.shape

torch.Size([3, 4])

In [39]:
g = torch.ones(5, 1, 4)
h = torch.ones(3, 4)
i = g + h

In [40]:
i.shape

torch.Size([5, 3, 4])

## 5. Practical broadcasting

In [14]:
matrix = torch.zeros(4, 3)
bias   = torch.tensor([1.0, 2.0, 3.0])

In [22]:
result = matrix + bias
row_bias = torch.tensor([10.0, 20.0, 30.0, 40.0])
result
result2 = matrix + row_bias.reshape(4, 1)
result2

tensor([[10., 10., 10.],
        [20., 20., 20.],
        [30., 30., 30.],
        [40., 40., 40.]])

# Exercise Set 3 — GPU

In [79]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using: {device}")

Using: cpu


In [80]:
x = torch.tensor([1.0, 2.0, 3.0], device=device)
y = torch.tensor([4.0, 5.0, 6.0], device=device)
z = x + y
z

tensor([5., 7., 9.])

In [24]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
a = torch.tensor([1.0, 2.0]).to(device)  # GPU
b = torch.tensor([3.0, 4.0])             # CPU

a + b

tensor([4., 6.])

In [26]:
def safe_matmul(a, b):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    a = a.to(device)
    b = b.to(device)
    return torch.matmul(a, b)

a = torch.randn(3, 4)
b = torch.randn(4, 5)
print(safe_matmul(a, b).shape)  # should be (3, 5)

torch.Size([3, 5])
